name: figozo_fl_practical
description: Figozo FL Practical App.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flex_color_scheme: ^6.0.1
  hive: ^2.2.3
  freezed_annotation: ^2.0.3
  dartz: ^0.10.1
  http: ^0.13.5
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: circular
      fonts:
        - asset: assets/fonts/Circular.otf
          weight: 400
        - asset: assets/fonts/Circular-Medium.otf
          weight: 500
        - asset: assets/fonts/Circular-Bold.otf
          weight: 600
